config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'
  
  get '/bi', to: 'business_intelligence#index'

  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :quantity, :price, presence: true
  validates :quantity, numericality: { greater_than_or_equal_to: 0 }
  validates :price, numericality: { greater_than: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/business_intelligence_controller.rb
class BusinessIntelligenceController < ApplicationController
  def index
    @total_products = Product.count
    @last_product = Product.all.last 
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :quantity)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/business_intelligence_helper.rb
module BusinessIntelligenceHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/business_intelligence/index.html.erb
<section class="section">
  <h1 class="title">Products quantity: <%= @total_products %></h1>

  <%= render "products/detail", product: @last_product, title: "Last added product" %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>SampleStock</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <section class="hero is-light is-fullheight">
    <!-- Hero head: will stick at the top -->
    <div class="hero-head">
      <header class="navbar">
        <div class="container">
          <div class="navbar-brand">
            <%= link_to "Sample Stock", root_path, class: "title", id: "logo" %>
            <span class="navbar-burger burger" data-target="navbarMenuHeroC">
              <span aria-hidden="true"></span>
              <span aria-hidden="true"></span>
              <span aria-hidden="true"></span>
            </span>
          </div>
          <div id="navbarMenuHeroC" class="navbar-menu">
            <div class="navbar-end">
              <%= link_to "Home", root_path, class: "navbar-item is-active" %>
              <%= link_to "Products", products_path, class: "navbar-item" %>
              <%= link_to "BI", bi_path, class: "navbar-item" %>
            </div>
          </div>
        </div>
      </header>
    </div>

    <!-- Hero content: will be in the middle -->
    <div class="hero-body">
      <div class="container">
        <div class="columns is-centered">
          <div class="column is-5-desktop is-5-widescreen">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
    </div>
  </section>
</body>

</html>

app/views/products/_detail.html.erb
<% if notice.present? %>
<p id="notice" class="notification is-primary"><%= notice %></p>
<% end %>
<div id="show">
  <h1 class="title"><%= title %></h1>
  <p>
    <strong class="subtitle">Name:</strong>
    <%= product.name %>
  </p>
  <p>
    <strong class="subtitle">Price:</strong>
    <%= number_to_currency(product.price) %>
  </p>
  <p>
    <strong class="subtitle">Quantity:</strong>
    <%= product.quantity %>
  </p>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2 class="subtitle"><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li class="notification is-danger"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, class: "label" %>
    <%= form.text_field :name, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :price, class: "label" %>
    <%= form.text_field :price, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :quantity, class: "label" %>
    <%= form.number_field :quantity, class: "input" %>
  </div>

  <div class="field is-grouped">
    <div class="control">
      <%= form.submit "Submit", class: "button is-info" %>
    </div>
  
    <div class="control">
      <%= link_to 'Back', products_path, class: "button is-info" %>
    </div>
  </div>
<% end %>

app/views/products/edit.html.erb
<section class="section">
  <h1 class="title">Editing Product</h1>
  
  <%= render 'form', product: @product %>
</section>

app/views/products/index.html.erb
<section class="section">
  <div class="columns is-centered">
    <div class="column is-narrow table-container">

      <% if notice.present? %>
        <p id="notice" class="notification is-primary"><%= notice %></p>
      <% end %>

      <h1 class="title">Products</h1>

      <table class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Price</th>
            <th>Quantity</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @products.each do |product| %>
          <tr>
            <td><%= product.name %></td>
            <td><%= number_to_currency(product.price) %></td>
            <td><%= product.quantity %></td>
            <td><%= link_to 'Show', product %></td>
            <td><%= link_to 'Edit', edit_product_path(product) %></td>
            <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Product', new_product_path, class: "button is-info" %>
    </div>
  </div>
</section>

app/views/products/new.html.erb
<section class="section">
  <h1 class="title">New Product</h1>

  <%= render 'form', product: @product %>
</section>

app/views/products/show.html.erb
<section class="section">
  <%= render 'detail', product: @product, title: "Product" %>

  <div class="field is-grouped">
    <div class="control">
      <%= link_to 'Edit', edit_product_path(product), class: "button is-info" %>
    </div>
    <div class="control">
      <%= link_to 'Destroy', product, class: "button is-info", method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
    <div class="control">
      <%= link_to 'Back', products_path, class: "button is-info" %>
    </div>
  </div>
</section>